apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketdb-deployment
  labels:
    app: basketdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketdb
  template:
    metadata:
      labels:
        app: basketdb
    spec:
      containers:
        - name: basketdb
          image: redis:alpine
          ports:
          - containerPort: 6379
          volumeMounts:
          - name: basketdb-host-volume
            mountPath: /var/lib/basketdb/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      volumes:
      - name: basketdb-host-volume
        hostPath:
          path: /host/data
---
apiVersion: v1
kind: Service
metadata:
  name: basketdb-service
spec:
  selector:
    app: basketdb
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
