apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb-deployment
  labels:
    app: catalogdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogdb
  template:
    metadata:
      labels:
        app: catalogdb
    spec:
      containers:
        - name: catalogdb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
          - name: catalogdb-host-volume
            mountPath: /catalogdb
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: catalogdb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalogdb-secret
                  key: mongo-root-password
      volumes:
      - name: catalogdb-host-volume
        hostPath:
          path: /host/data      
---
apiVersion: v1
kind: Service
metadata:
  name: catalogdb-service
spec:
  selector:
    app: catalogdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Secret
metadata:
  name: catalogdb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=