apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdb-deployment
  labels:
    app: orderdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
      - name: orderdb
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: orderdb-host-volume
          mountPath: /orderdb
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlserver-secret
              key: sa-password
      volumes:
      - name: orderdb-host-volume
        hostPath:
          path: /host/data      
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver-service
spec:
  selector:
    app: sqlserver
  ports:
  - name: sqlserver
    port: 1433
    targetPort: 1433
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
type: Opaque
data:
  sa-password: U3dOMTIzNDU2Nzg=  